/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "startapp.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*initSDK_t)(const char* DEVID, const char* APPID);

/**
 * struct that gets filled in by startappRegister
 */
typedef struct startappFuncs
{
    initSDK_t m_initSDK;
} startappFuncs;

static startappFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x693e0874, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: startapp");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x693e0874, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool startappAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult initSDK(const char* DEVID, const char* APPID)
{
    IwTrace(STARTAPP_VERBOSE, ("calling startapp[0] func: initSDK"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_initSDK(DEVID, APPID);
}
